src/Entity/Offers/Offers.php
<?php

namespace App\Entity\Offers;

use App\Entity\CandidateApplication\CandidatApplication;
use App\Entity\User\User;
use App\Repository\Offers\OffersRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OffersRepository::class)
 */
class Offers
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="offers")
     */
    private $IdUser;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Physique;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $HairLength;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $HairColor;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $EyeColor;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sex;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $GrowthMin;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $GrowthMax;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $AgeMax;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $AgeMin;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateAdd;

    /**
     * @ORM\OneToMany(targetEntity=CandidatApplication::class, mappedBy="Offer")
     */
    private $candidatApplications;

    public function __construct(

        User $IdUser,
        string $Title,
        string $Description,
        string $Physique,
        string $HairLength,
        string $HairColor,
        string $EyeColor,
        string $sex,
        ?int $GrowthMin,
        ?int $GrowthMax,
        ?int $AgeMax,
        ?int $AgeMin,
        bool $isActive=true
    )
    {
        $this->IdUser = $IdUser;
        $this->Title = $Title;
        $this->Description = $Description;
        $this->Physique = $Physique;
        $this->HairLength = $HairLength;
        $this->HairColor = $HairColor;
        $this->EyeColor = $EyeColor;
        $this->sex = $sex;
        $this->GrowthMin = $GrowthMin;
        $this->GrowthMax = $GrowthMax;
        $this->AgeMax = $AgeMax;
        $this->AgeMin = $AgeMin;
        $this->isActive = $isActive;
        $this->DateAdd=new DateTime('now');
        $this->candidatApplications = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return User
     */
    public function getIdUser(): User
    {
        return $this->IdUser;
    }

    public function addIdUser(User $idUser): self
    {
        if (!$this->IdUser->contains($idUser)) {
            $this->IdUser[] = $idUser;
            $idUser->setOffers($this);
        }

        return $this;
    }

    public function removeIdUser(User $idUser): self
    {
        if ($this->IdUser->contains($idUser)) {
            $this->IdUser->removeElement($idUser);
            // set the owning side to null (unless already changed)
            if ($idUser->getOffers() === $this) {
                $idUser->setOffers(null);
            }
        }

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPhysique(): ?string
    {
        return $this->Physique;
    }

    public function setPhysique(string $Physique): self
    {
        $this->Physique = $Physique;

        return $this;
    }

    public function getHairLength(): ?string
    {
        return $this->HairLength;
    }

    public function setHairLength(string $HairLength): self
    {
        $this->HairLength = $HairLength;

        return $this;
    }

    public function getHairColor(): ?string
    {
        return $this->HairColor;
    }

    public function setHairColor(string $HairColor): self
    {
        $this->HairColor = $HairColor;

        return $this;
    }

    public function getEyeColor(): ?string
    {
        return $this->EyeColor;
    }

    public function setEyeColor(string $EyeColor): self
    {
        $this->EyeColor = $EyeColor;

        return $this;
    }


    public function getSex(): ?string
    {
        return $this->sex;
    }

    public function setSex(string $sex): self
    {
        $this->sex = $sex;

        return $this;
    }

    public function getGrowthMin(): ?int
    {
        return $this->GrowthMin;
    }

    public function setGrowthMin(int $GrowthMin): self
    {
        $this->GrowthMin = $GrowthMin;

        return $this;
    }

    public function getGrowthMax(): ?int
    {
        return $this->GrowthMax;
    }

    public function setGrowthMax(int $GrowthMax): self
    {
        $this->GrowthMax = $GrowthMax;

        return $this;
    }

    public function getAgeMax(): ?int
    {
        return $this->AgeMax;
    }

    public function setAgeMax(int $AgeMax): self
    {
        $this->AgeMax = $AgeMax;

        return $this;
    }

    public function getAgeMin(): ?int
    {
        return $this->AgeMin;
    }

    public function setAgeMin(int $AgeMin): self
    {
        $this->AgeMin = $AgeMin;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getDateAdd(): ?\DateTime
    {
        return $this->DateAdd;
    }

    public function setDateAdd(\DateTime $DateAdd): self
    {
        $this->DateAdd = $DateAdd;

        return $this;
    }

    /**
     * @return Collection|CandidatApplication[]
     */
    public function getCandidatApplications(): Collection
    {
        return $this->candidatApplications;
    }

    public function addCandidatApplication(CandidatApplication $candidatApplication): self
    {
        if (!$this->candidatApplications->contains($candidatApplication)) {
            $this->candidatApplications[] = $candidatApplication;
            $candidatApplication->setOffer($this);
        }

        return $this;
    }

    public function removeCandidatApplication(CandidatApplication $candidatApplication): self
    {
        if ($this->candidatApplications->contains($candidatApplication)) {
            $this->candidatApplications->removeElement($candidatApplication);
            // set the owning side to null (unless already changed)
            if ($candidatApplication->getOffer() === $this) {
                $candidatApplication->setOffer(null);
            }
        }

        return $this;
    }
}

src/Controller/Candidat/CandidatController.php
<?php

namespace App\Controller\Candidat;

use App\Entity\CandidateProfil\CandidateProfil;
use App\Entity\CandidateProfil\UseCase\ChangePhoto;
use App\Entity\CandidateProfil\UseCase\EditCandidate;
use App\Entity\User\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class CandidatController extends AbstractController
{

    /**
     * @Route("/{_locale}/Candidat", name="HomePageCandidat")
     */
    public function main(){
        if ($this->getUser()==null) {
             return $this->redirectToRoute('locals');
         }

        return $this->render('Candidat/Candidat.html.twig',['user'=>$this->getUser(),
            'physiques'=>CandidateProfil::PHYSIQUES,
            'HairLengths'=>CandidateProfil::HAIRLENGTHS,
            'HairColors'=>CandidateProfil::HAIRCOLORS,
            'EyeColors'=>CandidateProfil::EYRCOLORS,
            'SEXs'=>CandidateProfil::SEX]);
    }

    /**
     * @Route("/{_locale}/Candidat/addCandidat", name="addCandidat")
     */
    public function addCandidat(Request $request,EditCandidate $editCandidate,ChangePhoto $photo){

        $formData =$request->request->all();


        if (isset($formData["isShow"])==false)
        {
            $isShow=false;
        }
        else{
            $isShow=true;
        }

        $command= new EditCandidate\Command($this->getUser()->getCandidateProfil(),$formData['growth'],$formData['physique'],$formData['HairLength'],$formData['HairColor'],$formData['EyeColor'],$formData['age'],$formData["sex"],$isShow);
        $editCandidate->execute($command);

        if ($request->files->get('file')!=null) {

            $file = $request->files->get('file');
            $uploads_directory = $this->getParameter('uploads_directory');
            $filename = md5(uniqid()) . '.' . $file->guessExtension();
            $file->move(
                $uploads_directory, $filename
            );
            $scrPhoto=$uploads_directory."/".$filename;

            /** @var User $user */
            $user=$this->getUser();
            $command=new ChangePhoto\Command($user,$scrPhoto);
            $photo->execute($command);

        }
        return $this->redirectToRoute('homepage');

    }

}

src/Controller/Candidat/OffersForCandidateController.php
<?php

namespace App\Controller\Candidat;

use App\Adapter\Offers\OffersQuery;
use App\Entity\Offers\Offers\ReadModel\OffersRead;
use App\Entity\User\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class OffersForCandidateController extends AbstractController
{
    /**
     * @Route("/{_locale}/Candidat/Offers", name="OffersCandidat")
     */
    public function offer(OffersQuery $offersQuery){
        if($this->getUser() == null){
            return $this->redirectToRoute('homepage');
        }

        /** @var User $user */
        $user = $this->getUser();

        $candidat = $user->getCandidateProfil();

        $Offers = null;
        $offers = $offersQuery->findForCandidat($candidat->getPhysique(), $candidat->getHairLength(), $candidat->getHairColor(), $candidat->getEyeColor(), $candidat->getSex(), $candidat->getGrowth(), $candidat->getAge());

        foreach ($offers as $offer){
            $Offers[] = new OffersRead($offer->getId(),
                $user,
                $offer->getTitle(),
                $offer->getDescription(),
                $offer->getPhysique(),
                $offer->getHairLength(),
                $offer->getHairColor(),
                $offer->getEyeColor(),
                $offer->getSex(),
                $offer->getGrowthMin(),
                $offer->getGrowthMax(),
                $offer->getAgeMax(),
                $offer->getAgeMin(),
                $offer->getIsActive(),
                $offer->getDateTime()
            );
        }
        return $this->render('Candidat/OffersForCandidate.html.twig', [
            'offers' => $Offers
        ]);
    }
}

templates/Candidat/Candidat.html.twig
{% extends 'base.html.twig' %}
{% set flashesbag = app.flashes %}


{% block body %}
<!------ Include the above in your HEAD tag ---------->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/Switch.css') }}">


<div class="container emp-profile text-black-50">
    <form method="post" id="form_id" action="{{ path('addCandidat') }}" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <img src="{{ asset(user.photo) }}" alt=""/>
                    <div class="file btn btn-lg btn-primary">
                        {{ "zmień zdjęcie"|trans }}
                        <input type="file" name="file" id="file"
                               accept=".jpg, .jpeg, .png" >

                    </div>

                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                    <h5>
                        {{ user.candidateProfil.FirstName }} {{ user.candidateProfil.Surname }}
                    </h5>
                    <label><input type="checkbox" id="isShow" name="isShow">Profil widoczny</label>
                </div>
            </div>
        </div>
            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Login</label>
                            </div>
                            <div class="col-md-6">
                                <p>
                                    {{ user.login }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Email</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ user.getemail }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>{{ "wzrost"|trans }}</label>
                            </div>
                            <div class="col-md-6">
                                <input type="number" name="growth" min="0" step="1" max="250" value="{{ user.getCandidateProfil.Growth }}"/>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label> {{"Płeć"|trans}}</label>
                            </div>
                            <div class="col-md-6">
                                <select id="sex" name="sex" class="form__input">
                                    <option {% if user.candidateProfil.Sex is null %}value="null">{{ "Wybierz"|trans }}{% else %}value="{{ user.candidateProfil.Sex }}">{{ user.candidateProfil.Sex }}{% endif %}</option>
                                    {% for sex in SEXs %}
                                        <option value="{{ sex }}">{{ sex }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label> {{"budowa ciała"|trans}}</label>
                            </div>
                            <div class="col-md-6">
                                <select id="physique" name="physique" class="form__input">
                                    <option {% if user.candidateProfil.physique is null %}value="null">{{ "Wybierz"|trans }}{% else %}value="{{ user.candidateProfil.physique }}">{{ user.candidateProfil.physique }}{% endif %}</option>
                                    {% for physique in physiques %}
                                        <option value="{{ physique }}">{{ physique }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>{{ "długość włosów"|trans }}</label>
                            </div>
                            <div class="col-md-6">
                                <select id="HairLength" name="HairLength" class="form__input">
                                    <option {% if user.candidateProfil.HairLength is null %}value="null">{{ "Wybierz"|trans }}{% else %}value="{{ user.candidateProfil.HairLength }}">{{ user.candidateProfil.HairLength }}{% endif %}</option>
                                    {% for HairLength in HairLengths %}
                                        <option value="{{ HairLength }}">{{ HairLength }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>{{ "kolor włosów"|trans }}</label>
                            </div>
                            <div class="col-md-6">
                                    <select id="HairColor" name="HairColor" class="form__input">
                                        <option {% if user.candidateProfil.HairColor is null %}value="null">{{ "Wybierz"|trans }}{% else %}value="{{ user.candidateProfil.HairColor }}">{{ user.candidateProfil.HairColor }}{% endif %}</option>
                                        {% for HairColor in HairColors %}
                                            <option value="{{ HairColor }}">{{ HairColor }}</option>
                                        {% endfor %}
                                    </select>

                                </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>{{ "kolor oczu"|trans }}</label>
                            </div>
                                <div class="col-md-6">
                                    <select id="EyeColor" name="EyeColor" class="form__input">
                                        <option {% if user.candidateProfil.EyeColor is null %}value="null">{{ "Wybierz"|trans }}{% else %}value="{{ user.candidateProfil.EyeColor }}">{{ user.candidateProfil.EyeColor }}{% endif %}</option>
                                        {% for EyeColor in EyeColors %}
                                            <option value="{{ EyeColor }}">{{ EyeColor }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div><div class="row">
                            <div class="col-md-6">
                                <label>{{ "wiek"|trans }}</label>
                            </div>
                            <div class="col-md-6">
                                <input type="number" name="age" min="0" step="1" max="100" value="{{ user.getCandidateProfil.Age }}"/>
                            </div>
                        </div>
                    </div>
                </div><div class="col align-self-end">
                    <input type="submit" class="profile-edit-btn" name="btnAddMore" value="{{ "Zapisz zmiany"|trans }}"/>
                </div>
    </form>
</div>
{% endblock %}
{% block javascripts %}
    <script
            src="https://code.jquery.com/jquery-3.5.1.js"
            integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
            crossorigin="anonymous"></script>
    <script>
    $("#isShow").on('change', function () {
        console.log(document.getElementById('isShow').checked)
        console.log({{ user.candidateProfil.isShow }})
    });
</script>

    <script>
        $(document).ready(function(){
          var tern ={{ user.candidateProfil.isShow }};
              console.log(tern);
            document.getElementById("isShow").checked = {{ user.candidateProfil.isShow }};

        });
    </script>
{% endblock %}

templates/Candidat/OffersForCandidate.html.twig
{% extends 'base.html.twig' %}
{% set flashesbag = app.flashes %}

{% block body %}

    <div class="container">
        <div class="row">

            {% if flashesbag.success is defined %}
                <div class="col-8 mx-auto bg-success border border-dark shadow rounded">
                    <p>{{ flashesbag.success[0] }}</p>
                </div>
            {% endif %}

            {% if offers == null %}
                <p>brak wyników wyszukiwaia</p>
            {% else %}
                {% for offer in offers %}
                    <div class="col-5 mx-auto bg-dark border border-dark shadow my-3 p-2">
                        <strong>Id ogłoszenia: {{ offer.id }}</strong>
                        <p>Tytuł: {{ offer.title}}</p>
                        <p>Treść: {{ offer.description }}</p>
                        <button id="Button{{ offer.id }}" onclick="myAction( '{{ offer.id }}' )" >Wyślij aplikację</button>
                    </div>

                {% endfor %}
            {% endif %}
        </div>
    </div>

{% endblock %}
{% block javascripts %}

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>

    <script>
        function myAction(valu){
            document.getElementById('Button'+valu).disabled = true;
            $.ajax({
                url: "{{ path('send_application',{'id':offers.id}) }}",
                method: "post",
                dataType:"json",
                data: {
                    valu
                },
                success: function (buttonn) {
                    document.getElementById(buttonn).disabled = true;
                    alert('Propozycja wysłana!');

                },
                error: function(buttonn){
                    alert('Błąd wysyłania!');
                    document.getElementById(buttonn).disabled = false;

                }

            });
        }
    </script>

    <script>
        $(document).ready(function(){
            $.ajax({
                url: "{{ path('loadButtonCandidat') }}",
                success: function (Buttonlist){

                    Array.prototype.forEach.call(Buttonlist, entry => {
                        document.getElementById(entry).disabled = true;
                    });

                }
            });
        });
        function disable(element, index, array) {
            document.getElementById("element").disabled = true;
            console.log("element");
``
        }
    </script>

{% endblock %}