src/Entity/Offers/Offers.php
<?php

namespace App\Entity\Offers;

use App\Entity\CandidateApplication\CandidatApplication;
use App\Entity\User\User;
use App\Repository\Offers\OffersRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OffersRepository::class)
 */
class Offers
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="offers")
     */
    private $IdUser;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Physique;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $HairLength;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $HairColor;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $EyeColor;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sex;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $GrowthMin;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $GrowthMax;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $AgeMax;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $AgeMin;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateAdd;

    /**
     * @ORM\OneToMany(targetEntity=CandidatApplication::class, mappedBy="Offer")
     */
    private $candidatApplications;

    public function __construct(

        User $IdUser,
        string $Title,
        string $Description,
        string $Physique,
        string $HairLength,
        string $HairColor,
        string $EyeColor,
        string $sex,
        ?int $GrowthMin,
        ?int $GrowthMax,
        ?int $AgeMax,
        ?int $AgeMin,
        bool $isActive=true
    )
    {
        $this->IdUser = $IdUser;
        $this->Title = $Title;
        $this->Description = $Description;
        $this->Physique = $Physique;
        $this->HairLength = $HairLength;
        $this->HairColor = $HairColor;
        $this->EyeColor = $EyeColor;
        $this->sex = $sex;
        $this->GrowthMin = $GrowthMin;
        $this->GrowthMax = $GrowthMax;
        $this->AgeMax = $AgeMax;
        $this->AgeMin = $AgeMin;
        $this->isActive = $isActive;
        $this->DateAdd=new DateTime('now');
        $this->candidatApplications = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return User
     */
    public function getIdUser(): User
    {
        return $this->IdUser;
    }

    public function addIdUser(User $idUser): self
    {
        if (!$this->IdUser->contains($idUser)) {
            $this->IdUser[] = $idUser;
            $idUser->setOffers($this);
        }

        return $this;
    }

    public function removeIdUser(User $idUser): self
    {
        if ($this->IdUser->contains($idUser)) {
            $this->IdUser->removeElement($idUser);
            // set the owning side to null (unless already changed)
            if ($idUser->getOffers() === $this) {
                $idUser->setOffers(null);
            }
        }

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPhysique(): ?string
    {
        return $this->Physique;
    }

    public function setPhysique(string $Physique): self
    {
        $this->Physique = $Physique;

        return $this;
    }

    public function getHairLength(): ?string
    {
        return $this->HairLength;
    }

    public function setHairLength(string $HairLength): self
    {
        $this->HairLength = $HairLength;

        return $this;
    }

    public function getHairColor(): ?string
    {
        return $this->HairColor;
    }

    public function setHairColor(string $HairColor): self
    {
        $this->HairColor = $HairColor;

        return $this;
    }

    public function getEyeColor(): ?string
    {
        return $this->EyeColor;
    }

    public function setEyeColor(string $EyeColor): self
    {
        $this->EyeColor = $EyeColor;

        return $this;
    }


    public function getSex(): ?string
    {
        return $this->sex;
    }

    public function setSex(string $sex): self
    {
        $this->sex = $sex;

        return $this;
    }

    public function getGrowthMin(): ?int
    {
        return $this->GrowthMin;
    }

    public function setGrowthMin(int $GrowthMin): self
    {
        $this->GrowthMin = $GrowthMin;

        return $this;
    }

    public function getGrowthMax(): ?int
    {
        return $this->GrowthMax;
    }

    public function setGrowthMax(int $GrowthMax): self
    {
        $this->GrowthMax = $GrowthMax;

        return $this;
    }

    public function getAgeMax(): ?int
    {
        return $this->AgeMax;
    }

    public function setAgeMax(int $AgeMax): self
    {
        $this->AgeMax = $AgeMax;

        return $this;
    }

    public function getAgeMin(): ?int
    {
        return $this->AgeMin;
    }

    public function setAgeMin(int $AgeMin): self
    {
        $this->AgeMin = $AgeMin;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getDateAdd(): ?\DateTime
    {
        return $this->DateAdd;
    }

    public function setDateAdd(\DateTime $DateAdd): self
    {
        $this->DateAdd = $DateAdd;

        return $this;
    }

    /**
     * @return Collection|CandidatApplication[]
     */
    public function getCandidatApplications(): Collection
    {
        return $this->candidatApplications;
    }

    public function addCandidatApplication(CandidatApplication $candidatApplication): self
    {
        if (!$this->candidatApplications->contains($candidatApplication)) {
            $this->candidatApplications[] = $candidatApplication;
            $candidatApplication->setOffer($this);
        }

        return $this;
    }

    public function removeCandidatApplication(CandidatApplication $candidatApplication): self
    {
        if ($this->candidatApplications->contains($candidatApplication)) {
            $this->candidatApplications->removeElement($candidatApplication);
            // set the owning side to null (unless already changed)
            if ($candidatApplication->getOffer() === $this) {
                $candidatApplication->setOffer(null);
            }
        }

        return $this;
    }
}

src/Form/Candidates/FiltrCandidatesType.php
<?php


namespace App\Form\Candidates;


use App\Entity\CandidateProfil\CandidateProfil;
use Doctrine\ORM\Mapping\Entity;
use phpDocumentor\Reflection\Types\Integer;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
class FiltrCandidatesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('growthMin', IntegerType::class,[
                'attr' =>[
                    'step'=>1,
                    'min' =>0,
                    'max'=>250,
                    'value'=>0,
                    'label'=>"Wzrost Minimalny"
                ],

            ])
            ->add('growthMax', IntegerType::class,[
                'attr' =>[
                    'step'=>1,
                    'min' =>0,
                    'max'=>250,
                    'value'=>250,
                    'label'=>"Wzrost Maxymalny"
                ]
            ])
            ->add('physique', ChoiceType::class, [
                'attr' => [
                'class' => CandidateProfil::class,
    ],
                'label' => 'Sylwetka',

                'choices' => [array_flip(CandidateProfil::PHYSIQUES),'Dowolna'=>'default'],
                'data'=>'default'
            ])
            ->add('hair_length', ChoiceType::class, [
                'attr' => [
                    'class' => CandidateProfil::class
                ],
                'label' => 'Włosy',
                'choices' => [array_flip(CandidateProfil::HAIRLENGTHS),'Dowolna'=>'default'],
                'data'=>'default'
            ])
            ->add('hair_color', ChoiceType::class, [
                'attr' => [
                    'class' => CandidateProfil::class
                ],
                'label' => 'Kolor włosów',
                'choices' => [array_flip(CandidateProfil::HAIRCOLORS),'Dowolna'=>'default'],
                'data'=>'default'
            ])
            ->add('eye_color', ChoiceType::class, [
                'attr' => [
                    'class' => CandidateProfil::class
                ],
                'label' => 'Kolor oczu',
                'choices' => [array_flip(CandidateProfil::EYRCOLORS),'Dowolna'=>'default'],
                'data'=>'default'
            ])
            ->add('sex', ChoiceType::class, [
                'attr' => [
                    'class' => CandidateProfil::class
                ],
                'label' => 'Płeć',
                'choices' => [array_flip(CandidateProfil::SEX),'Dowolna'=>'default'],
                'data'=>'default'
            ])
            ->add('AgeMin', IntegerType::class,[
                'attr' =>[
                    'step'=>1,
                    'min' =>0,
                    'max'=>100,
                    'value'=>0,
                    'label'=>'Wiek Minimalny'
                ]
            ])
            ->add('AgeMax', IntegerType::class,[
                'attr' =>[
                    'step'=>1,
                    'min' =>0,
                    'max'=>100,
                    'value'=>100,
                    'label'=>'Wiek Maxymalny']
            ])
        ;
    }
}

src/Controller/Candidates/CandidatesFilterController.php
<?php


namespace App\Controller\Candidates;


use App\Adapter\CandidateProfile\CandidateQuery;
use App\Adapter\User\Users;
use App\Entity\CandidateProfil\ReadModel\CandidateProfileandUser;
use App\Form\Candidates\FiltrCandidatesType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class CandidatesFilterController extends AbstractController
{
    /**
     * @Route("/{_locale}/group/filter/candidate", name="filter_candidate")
     */
    public function main(Request $request, CandidateQuery $candidateQuery, Users $users)
    {
        $form = $this->createForm(FiltrCandidatesType::class, []);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $data = $form->getData();
            if ($data['growthMax'] < $data['growthMin']) {
                $data['growthMax'] = $data['growthMin'];
            }
            if ($data['AgeMax'] < $data['AgeMin']) {
                $data['AgeMax'] = $data['AgeMin'];
            }
            if ($data['physique'] == 'default') {
                $physique = 'is not null';
            } else {
                $physique = "= '" . $data['physique'] . "'";
            }
            if ($data['hair_length'] == 'default') {
                $HairLength = 'is not null';
            } else {
                $HairLength = "= '" . $data['hair_length'] . "'";
            }
            if ($data['hair_color'] == 'default') {
                $HairColor = 'is not null';
            } else {
                $HairColor = "= '" . $data['hair_color'] . "'";
            }
            if ($data['eye_color'] == 'default') {
                $EyeColor = 'is not null';
            } else {
                $EyeColor = "= '" . $data['eye_color'] . "'";
            }
            if ($data['sex'] == 'default') {
                $sex = 'is not null';
            } else {
                $sex = "= '" . $data['sex'] . "'";
            }


            $Candidates=null;
                $candidates = $candidateQuery->getfilter($data['growthMin'], $data['growthMax'], $physique, $HairLength, $HairColor, $EyeColor, $data['AgeMin'], $data['AgeMax'],$sex);
            foreach ($candidates as $candidate) {
                $Candidates[] = new CandidateProfileandUser($candidate->getId(),$users->findById($candidate->getUser()),$candidate->getGrowth(),
                    $candidate->getPhysique(),
                $candidate->getHairLength(),
                $candidate->getHairColor(),
                $candidate->getEyeColor(),
                $candidate->getAge(),
                $candidate->getSurname(),
                $candidate->getFirstName(),
                $candidate->getSex());
}
            return $this->render('Candidates/listCandidate.html.twig', [
                'candidates' => $Candidates
            ]);
        }

        return $this->render('Candidates/FilterCandidates.html.twig', [
            'form' => $form->createView(),
        ]);


    }

}

src/Controller/Candidates/LoadSendOfferController.php
<?php


namespace App\Controller\Candidates;


use App\Adapter\SendOfferBusiness\SendOfferBusiness;
use App\Adapter\SendOfferGroup\SendOfferGroup;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

class LoadSendOfferController extends AbstractController
{
    /**
     * @var SendOfferGroup
     */
    private $group;
    /**
     * @var SendOfferBusiness
     */
    private $business;

    public function __construct(
        SendOfferGroup $group,
        SendOfferBusiness $business
    )
    {
        $this->group = $group;
        $this->business = $business;
    }

    /**
     * @Route("/{_locale}/group/loadbutton", name="loadButton")
     */
    public function main()
    {   $date = new \DateTime("-15 day");
        if ($this->getUser()->getRoles() == ['ROLE_GROUP']) {
            $Groups = $this->group->LoadAllByIdGroup($this->getUser()->getActorGrupe()->getId());
            foreach ($Groups as $Group) {
                if ($Group->getSendDate()->getTimestamp() > $date->getTimestamp()) {
                    $groups[] = "Button" . $Group->getCandidat()->getUser()->getLogin();

                }
            }
        } else if ($this->getUser()->getRoles() == ['ROLE_BUSINESS']) {
            $Groups = $this->business->LoadAllByIdBusiness($this->getUser()->getBusiness()->getId());
            foreach ($Groups as $Group) {
                if ($Group->getSendData()->getTimestamp() > $date->getTimestamp()) {
                    $groups[] = "Button" . $Group->getCandidate()->getUser()->getLogin();

                }
            }
        }



        return new JsonResponse($groups);
    }

}

src/Controller/Candidates/SendEmailToCandidatController.php
<?php

namespace App\Controller\Candidates;

use App\Adapter\User\Users;
use App\Entity\SendOfferBusiness\UseCase\CreateSendOfferBuisness;
use App\Entity\SendOfferBusiness\UseCase\CreateSendOfferBuisness\Command;
use App\Entity\SendOfferGrupe\UseCase\CreateSendOfferGroup;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

class SendEmailToCandidatController extends AbstractController
{
    private $mailer;
    /**
     * @var Users
     */
    private $users;

    public function __construct(\Swift_Mailer $mailer,Users $users )
    {
        $this->mailer = $mailer;
        $this->users = $users;
    }

    /**
     * @Route("/{_locale}/group/send/", name="send_candidate_mail")
     */
    public function main(CreateSendOfferBuisness $createSendOfferBuisness,CreateSendOfferGroup $createSendOfferGroup ){
        $data = $_REQUEST['valu'];
        if ($this->getUser()->getRoles()==['ROLE_GROUP'])
        {
            $command = new CreateSendOfferGroup\Command($this->getUser()->getActorGrupe(),$this->users->findByUserName($data)->getCandidateProfil());
            $createSendOfferGroup->execute($command);
            return new JsonResponse('Button'.$data);

        }else if ($this->getUser()->getRoles()==["ROLE_BUSINESS"])
        {

            $command = new Command($this->getUser()->getBusiness(),$this->users->findByUserName($data)->getCandidateProfil());
            $createSendOfferBuisness->execute($command);
            return new JsonResponse('Button'.$data);

        }
        return new JsonResponse('error');

    }
}

templates/Candidates/FilterCandidates.html.twig
{% extends 'baseGroupe.html.twig' %}
{% set flashesbag = app.flashes %}

{% block title %}Log in!{% endblock %}
{% block body %}

    <div class="container">
    <div class="row">
    <div class="col">
    </div>
    <div class="text-center">
    {% if flashesbag.success is defined %}
        <div class="col-8 mx-auto bg-success border border-dark shadow rounded">
            <p>{{ flashesbag.success[0] }}</p>
        </div>
    {% endif %}

    {% if flashesbag.error is defined %}
        <div class="col-8 mx-auto bg-success border border-dark shadow rounded">
            <p>{{ flashesbag.error[0] }}</p>
        </div>
    {% endif %}


    {{ form_start(form) }}
    {{ form_row(form.growthMin) }}
        {{ form_row(form.growthMax) }}
        {{ form_row(form.physique) }}
        {{ form_row(form.hair_length) }}
        {{ form_row(form.hair_color) }}
        {{ form_row(form.eye_color) }}
        {{ form_row(form.sex) }}
        {{ form_row(form.AgeMin) }}
        {{ form_row(form.AgeMax) }}

    <button type="submit" class="btn"> szukaj</button>
    {{ form_end(form) }}

    </div>    <div class="col">
        </div>
    </div>
    </div>
{% endblock %}

templates/Candidates/listCandidate.html.twig
{% extends 'baseGroupe.html.twig' %}
{% set flashesbag = app.flashes %}

{% block body %}

    <div class="container">
        <div class="row">

            {% if flashesbag.success is defined %}
                <div class="col-8 mx-auto bg-success border border-dark shadow rounded">
                    <p>{{ flashesbag.success[0] }}</p>
                </div>
            {% endif %}

            {% if candidates == null %}
            <p>brak wyników wyszukiwaia</p>
            {% else %}
            {% for candidate in candidates %}
                <div class="col-5 mx-auto bg-dark border border-dark shadow my-3 p-2">
                    <div class="d-inline-block">
                        <div class="col-md-4">
                            <div class="profile-img">
                                <img src="{{ asset(candidate.user.photo) }}" alt=""/>
                                </div>
                            </div>
                    </div>
                   <strong>Imię: {{ candidate.Surname }}</strong>
                    <p>Wzrost: {{ candidate.growth }}</p>
                    <p>Sylwetka: {{ candidate.physique }}</p>
                    <p>Rodzaj włosów: {{ candidate.hairLength }}</p>
                    <p>Kolor włosów: {{ candidate.hairColor }}</p>
                    <p>Kolor oczu: {{ candidate.eyeColor }}</p>
                    <p>Wiek: {{ candidate.age }}</p>
                    {% if app.request.get('_locale') == 'en' %}
                    <p>Płeć: {{ candidate.sex }}</p>
                    {% else %}
                        {%  if  candidate.sex == 'woman' %}
                        <p>Płeć: Kobieta</p>
                        {% else %}
                            <p>Płeć: Meżczyzna</p>
                            {% endif %}{% endif %}
                            <button id="Button{{ candidate.user.login }}" onclick="myAction( '{{ candidate.user.login }}' )" >Wyślij</button>

                </div>

            {% endfor %}
{% endif %}
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>

    <script>
        function myAction(valu){
            document.getElementById('Button'+valu).disabled = true;
            $.ajax({
                url: "{{ path('send_candidate_mail') }}",
                method: "post",
                dataType:"json",
                data: {
                    valu
                },
                success: function (buttonn) {
                    document.getElementById(buttonn).disabled = true;
                    alert('Propozycja wysłana!');

                },
                error: function(buttonn){
                    alert('Błąd wysyłania!');
                    document.getElementById(buttonn).disabled = false;

                }

                });
        }
    </script>

    <script>
        $(document).ready(function(){
            $.ajax({
                url: "{{ path('loadButton') }}",
                success: function (Buttonlist){

                    Array.prototype.forEach.call(Buttonlist, entry => {
                        document.getElementById(entry).disabled = true;
                    });

                }
            });
        });
        function disable(element, index, array) {
            document.getElementById("element").disabled = true;
            console.log("element");

        }
    </script>
    
{% endblock %}